# Employee Performance Analysis

## Data Processing

### Project Objective

The objective of this project is to analyze employee performance data, identify the key factors associated with employee performance, develop a machine learning model for predicting employee performance, and provide actionable recommendations based on the analysis.

This project is based on the INX Future Inc. Employee Performance Analysis case study provided by IABAC.

# Employee Performance Analysis

## 1. Data Processing

### 1.1 Load the Raw Dataset

The original employee performance dataset is loaded from the raw data directory.

The raw dataset is preserved without modification. A separate working copy is created for data quality checks, cleaning, and preprocessing.

This approach maintains a clear distinction between the original source data and the processed dataset used for analysis and modeling.

In [1]:
import pandas as pd
import numpy as np

# Display all columns when viewing DataFrames
pd.set_option("display.max_columns", None)

# Path to the original dataset
file_path = "../../data/raw/INX_Future_Inc_Employee_Performance_CDS_Project2_Data_V1.8.xls"

# Load the original dataset
df_raw = pd.read_excel(
    file_path,
    sheet_name="INX_Future_Inc_Employee_Perform"
)

# Create a working copy
df = df_raw.copy()

print("Dataset loaded successfully.")
print(f"Rows    : {df_raw.shape[0]}")
print(f"Columns : {df_raw.shape[1]}")

Dataset loaded successfully.
Rows    : 1200
Columns : 28

### 1.2 Initial Dataset Inspection

The initial inspection is performed to understand the structure of the dataset before applying any data cleaning or transformation.

The inspection includes:

- Dataset dimensions
- Column names
- Data types
- Initial records
- Numerical and categorical variables
- Missing values
- Duplicate records
- Unique values
- Target variable distribution

In [2]:
# Display the first 5 records
df.head()

,EmpNumber,Age,Gender,EducationBackground,MaritalStatus,EmpDepartment,EmpJobRole,BusinessTravelFrequency,DistanceFromHome,EmpEducationLevel,EmpEnvironmentSatisfaction,EmpHourlyRate,EmpJobInvolvement,EmpJobLevel,EmpJobSatisfaction,NumCompaniesWorked,OverTime,EmpLastSalaryHikePercent,EmpRelationshipSatisfaction,TotalWorkExperienceInYears,TrainingTimesLastYear,EmpWorkLifeBalance,ExperienceYearsAtThisCompany,ExperienceYearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition,PerformanceRating
0,E1001000,32,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,10,3,4,55,3,2,4,1,No,12,4,10,2,2,10,7,0,8,No,3
1,E1001006,47,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,14,4,4,42,3,2,1,2,No,12,4,20,2,3,7,7,1,7,No,3
2,E1001007,40,Male,Life Sciences,Married,Sales,Sales Executive,Travel_Frequently,5,4,4,48,2,3,1,5,Yes,21,3,20,2,3,18,13,1,12,No,4
3,E1001009,41,Male,Human Resources,Divorced,Human Resources,Manager,Travel_Rarely,10,4,2,73,2,5,4,3,No,15,2,23,2,2,21,6,12,6,No,3
4,E1001010,60,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,16,4,1,84,3,2,1,8,No,14,4,10,1,3,2,2,2,2,No,3

In [3]:
# Display the last 5 records
df.tail()

,EmpNumber,Age,Gender,EducationBackground,MaritalStatus,EmpDepartment,EmpJobRole,BusinessTravelFrequency,DistanceFromHome,EmpEducationLevel,EmpEnvironmentSatisfaction,EmpHourlyRate,EmpJobInvolvement,EmpJobLevel,EmpJobSatisfaction,NumCompaniesWorked,OverTime,EmpLastSalaryHikePercent,EmpRelationshipSatisfaction,TotalWorkExperienceInYears,TrainingTimesLastYear,EmpWorkLifeBalance,ExperienceYearsAtThisCompany,ExperienceYearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition,PerformanceRating
1195,E100992,27,Female,Medical,Divorced,Sales,Sales Executive,Travel_Frequently,3,1,4,71,4,2,4,1,Yes,20,2,6,3,3,6,5,0,4,No,4
1196,E100993,37,Male,Life Sciences,Single,Development,Senior Developer,Travel_Rarely,10,2,4,80,4,1,4,3,No,17,1,4,2,3,1,0,0,0,No,3
1197,E100994,50,Male,Medical,Married,Development,Senior Developer,Travel_Rarely,28,1,4,74,4,1,3,1,Yes,11,3,20,3,3,20,8,3,8,No,3
1198,E100995,34,Female,Medical,Single,Data Science,Data Scientist,Travel_Rarely,9,3,4,46,2,3,2,1,No,14,2,9,3,4,8,7,7,7,No,3
1199,E100998,24,Female,Life Sciences,Single,Sales,Sales Executive,Travel_Rarely,3,2,1,65,3,2,3,9,No,14,1,4,3,3,2,2,2,0,Yes,2

In [4]:
# Dataset dimensions
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 1200
Number of columns: 28

In [5]:
# Column names
print("Column names:")
for i, column in enumerate(df.columns, start=1):
    print(f"{i}. {column}")

Column names:
1. EmpNumber
2. Age
3. Gender
4. EducationBackground
5. MaritalStatus
6. EmpDepartment
7. EmpJobRole
8. BusinessTravelFrequency
9. DistanceFromHome
10. EmpEducationLevel
11. EmpEnvironmentSatisfaction
12. EmpHourlyRate
13. EmpJobInvolvement
14. EmpJobLevel
15. EmpJobSatisfaction
16. NumCompaniesWorked
17. OverTime
18. EmpLastSalaryHikePercent
19. EmpRelationshipSatisfaction
20. TotalWorkExperienceInYears
21. TrainingTimesLastYear
22. EmpWorkLifeBalance
23. ExperienceYearsAtThisCompany
24. ExperienceYearsInCurrentRole
25. YearsSinceLastPromotion
26. YearsWithCurrManager
27. Attrition
28. PerformanceRating

### 1.3 Data Types and Dataset Structure

Understanding the data type of each variable is important because numerical and categorical variables require different preprocessing techniques during machine learning.

In [6]:
# Data types and non-null counts
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 28 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   EmpNumber                     1200 non-null   str
 1   Age                           1200 non-null   int64
 2   Gender                        1200 non-null   str
 3   EducationBackground           1200 non-null   str
 4   MaritalStatus                 1200 non-null   str
 5   EmpDepartment                 1200 non-null   str
 6   EmpJobRole                    1200 non-null   str
 7   BusinessTravelFrequency       1200 non-null   str
 8   DistanceFromHome              1200 non-null   int64
 9   EmpEducationLevel             1200 non-null   int64
 10  EmpEnvironmentSatisfaction    1200 non-null   int64
 11  EmpHourlyRate                 1200 non-null   int64
 12  EmpJobInvolvement             1200 non-null   int64
 13  EmpJobLevel                   1200 non-null   int64
 14  EmpJobSatisfaction            1200 non-null   int64
 15  NumCompaniesWorked            1200 non-null   int64
 16  OverTime                      1200 non-null   str
 17  EmpLastSalaryHikePercent      1200 non-null   int64
 18  EmpRelationshipSatisfaction   1200 non-null   int64
 19  TotalWorkExperienceInYears    1200 non-null   int64
 20  TrainingTimesLastYear         1200 non-null   int64
 21  EmpWorkLifeBalance            1200 non-null   int64
 22  ExperienceYearsAtThisCompany  1200 non-null   int64
 23  ExperienceYearsInCurrentRole  1200 non-null   int64
 24  YearsSinceLastPromotion       1200 non-null   int64
 25  YearsWithCurrManager          1200 non-null   int64
 26  Attrition                     1200 non-null   str
 27  PerformanceRating             1200 non-null   int64
dtypes: int64(19), str(9)
memory usage: 262.6 KB

In [7]:
# Data type summary
data_types = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.astype(str).values,
    "Unique Values": [df[col].nunique() for col in df.columns],
    "Missing Values": [df[col].isna().sum() for col in df.columns]
})

data_types

                          Column Data Type  Unique Values  Missing Values
0                      EmpNumber       str           1200               0
1                            Age     int64             43               0
2                         Gender       str              2               0
3            EducationBackground       str              6               0
4                  MaritalStatus       str              3               0
5                  EmpDepartment       str              6               0
6                     EmpJobRole       str             19               0
7        BusinessTravelFrequency       str              3               0
8               DistanceFromHome     int64             29               0
9              EmpEducationLevel     int64              5               0
10    EmpEnvironmentSatisfaction     int64              4               0
11                 EmpHourlyRate     int64             71               0
12             EmpJobInvolvement     int64              4               0
13                   EmpJobLevel     int64              5               0
14            EmpJobSatisfaction     int64              4               0
15            NumCompaniesWorked     int64             10               0
16                      OverTime       str              2               0
17      EmpLastSalaryHikePercent     int64             15               0
18   EmpRelationshipSatisfaction     int64              4               0
19    TotalWorkExperienceInYears     int64             40               0
20         TrainingTimesLastYear     int64              7               0
21            EmpWorkLifeBalance     int64              4               0
22  ExperienceYearsAtThisCompany     int64             37               0
23  ExperienceYearsInCurrentRole     int64             19               0
24       YearsSinceLastPromotion     int64             16               0
25          YearsWithCurrManager     int64             18               0
26                     Attrition       str              2               0
27             PerformanceRating     int64              3               0

### 1.4 Missing-Value Analysis

Missing values are checked before data preprocessing because machine learning algorithms generally require appropriately handled input values.

The number and percentage of missing observations are examined for every variable.

In [8]:
missing_summary = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percentage": (df.isnull().sum() / len(df) * 100).round(2)
})

missing_summary = missing_summary.sort_values(
    by="Missing Count",
    ascending=False
)

missing_summary

                              Missing Count  Missing Percentage
EmpNumber                                 0                 0.0
Age                                       0                 0.0
Gender                                    0                 0.0
EducationBackground                       0                 0.0
MaritalStatus                             0                 0.0
EmpDepartment                             0                 0.0
EmpJobRole                                0                 0.0
BusinessTravelFrequency                   0                 0.0
DistanceFromHome                          0                 0.0
EmpEducationLevel                         0                 0.0
EmpEnvironmentSatisfaction                0                 0.0
EmpHourlyRate                             0                 0.0
EmpJobInvolvement                         0                 0.0
EmpJobLevel                               0                 0.0
EmpJobSatisfaction                        0                 0.0
NumCompaniesWorked                        0                 0.0
OverTime                                  0                 0.0
EmpLastSalaryHikePercent                  0                 0.0
EmpRelationshipSatisfaction               0                 0.0
TotalWorkExperienceInYears                0                 0.0
TrainingTimesLastYear                     0                 0.0
EmpWorkLifeBalance                        0                 0.0
ExperienceYearsAtThisCompany              0                 0.0
ExperienceYearsInCurrentRole              0                 0.0
YearsSinceLastPromotion                   0                 0.0
YearsWithCurrManager                      0                 0.0
Attrition                                 0                 0.0
PerformanceRating                         0                 0.0

In [9]:
# Check whether the dataset contains any missing values
total_missing = df.isnull().sum().sum()

print("Total missing values:", total_missing)

Total missing values: 0

### 1.5 Duplicate-Record Analysis

Duplicate records are identified to determine whether the dataset contains repeated observations.

Duplicate records can introduce unintended weighting during analysis and model training, so they are assessed before further processing.

In [10]:
# Count completely duplicated rows
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

### 1.6 Numerical Variable Summary

Descriptive statistics are generated for numerical variables to understand their central tendency, dispersion, and range.

These statistics also provide an initial indication of variables that may require further investigation for unusual values or outliers.

In [11]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,1200.0,36.918333,9.087289,18.0,30.0,36.0,43.0,60.0
DistanceFromHome,1200.0,9.165833,8.176636,1.0,2.0,7.0,14.0,29.0
EmpEducationLevel,1200.0,2.892500,1.044120,1.0,2.0,3.0,4.0,5.0
EmpEnvironmentSatisfaction,1200.0,2.715833,1.090599,1.0,2.0,3.0,4.0,4.0
EmpHourlyRate,1200.0,65.981667,20.211302,30.0,48.0,66.0,83.0,100.0
EmpJobInvolvement,1200.0,2.731667,0.707164,1.0,2.0,3.0,3.0,4.0
EmpJobLevel,1200.0,2.067500,1.107836,1.0,1.0,2.0,3.0,5.0
EmpJobSatisfaction,1200.0,2.732500,1.100888,1.0,2.0,3.0,4.0,4.0
NumCompaniesWorked,1200.0,2.665000,2.469384,0.0,1.0,2.0,4.0,9.0
EmpLastSalaryHikePercent,1200.0,15.222500,3.625918,11.0,12.0,14.0,18.0,25.0
EmpRelationshipSatisfaction,1200.0,2.725000,1.075642,1.0,2.0,3.0,4.0,4.0
TotalWorkExperienceInYears,1200.0,11.330000,7.797228,0.0,6.0,10.0,15.0,40.0
TrainingTimesLastYear,1200.0,2.785833,1.263446,0.0,2.0,3.0,3.0,6.0
EmpWorkLifeBalance,1200.0,2.744167,0.699374,1.0,2.0,3.0,3.0,4.0
ExperienceYearsAtThisCompany,1200.0,7.077500,6.236899,0.0,3.0,5.0,10.0,40.0
ExperienceYearsInCurrentRole,1200.0,4.291667,3.613744,0.0,2.0,3.0,7.0,18.0
YearsSinceLastPromotion,1200.0,2.194167,3.221560,0.0,0.0,1.0,3.0,15.0
YearsWithCurrManager,1200.0,4.105000,3.541576,0.0,2.0,3.0,7.0,17.0
PerformanceRating,1200.0,2.948333,0.518866,2.0,3.0,3.0,3.0,4.0

In [12]:
# Identify categorical columns
categorical_columns = df.select_dtypes(
    include=["object", "category"]
).columns.tolist()

print("Categorical columns:")
for column in categorical_columns:
    print(column)

Categorical columns:
EmpNumber
Gender
EducationBackground
MaritalStatus
EmpDepartment
EmpJobRole
BusinessTravelFrequency
OverTime
Attrition

C:\Users\HP\AppData\Local\Temp\ipykernel_20320\3789119200.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(

In [13]:
# Identify numerical columns
numerical_columns = df.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

print("Numerical columns:")
for column in numerical_columns:
    print(column)

Numerical columns:
Age
DistanceFromHome
EmpEducationLevel
EmpEnvironmentSatisfaction
EmpHourlyRate
EmpJobInvolvement
EmpJobLevel
EmpJobSatisfaction
NumCompaniesWorked
EmpLastSalaryHikePercent
EmpRelationshipSatisfaction
TotalWorkExperienceInYears
TrainingTimesLastYear
EmpWorkLifeBalance
ExperienceYearsAtThisCompany
ExperienceYearsInCurrentRole
YearsSinceLastPromotion
YearsWithCurrManager
PerformanceRating

### 1.7 Target Variable: Performance Rating

`PerformanceRating` is treated as the target variable because the project requires a trained model capable of predicting employee performance from relevant employee and organizational factors.

The distribution of the target classes is examined before model development to determine whether the classification problem is balanced or imbalanced.

In [14]:
# Target variable distribution
target_counts = df["PerformanceRating"].value_counts().sort_index()

print("Performance Rating Distribution:")
print(target_counts)

Performance Rating Distribution:
PerformanceRating
2    194
3    874
4    132
Name: count, dtype: int64

In [15]:
target_distribution = pd.DataFrame({
    "Count": target_counts,
    "Percentage": (target_counts / len(df) * 100).round(2)
})

target_distribution

                   Count  Percentage
PerformanceRating
2                    194       16.17
3                    874       72.83
4                    132       11.00

### 1.8 Variable-Level Data Understanding

Each variable is examined through its data type, number of unique values, minimum and maximum values where applicable, and representative categories.

This assessment helps distinguish continuous numerical variables, ordinal variables, nominal categorical variables, identifier variables, and the target variable before preprocessing.

In [16]:
# Create a compact variable-level summary

variable_summary = []

for column in df.columns:
    variable_info = {
        "Column": column,
        "Data Type": str(df[column].dtype),
        "Unique Values": df[column].nunique(),
        "Missing Values": df[column].isna().sum()
    }

    if pd.api.types.is_numeric_dtype(df[column]):
        variable_info["Minimum"] = df[column].min()
        variable_info["Maximum"] = df[column].max()
        variable_info["Example Values"] = sorted(
            df[column].unique()
        )[:10]
    else:
        variable_info["Minimum"] = "-"
        variable_info["Maximum"] = "-"
        variable_info["Example Values"] = df[column].unique()[:10].tolist()

    variable_summary.append(variable_info)

variable_summary_df = pd.DataFrame(variable_summary)

variable_summary_df

,Column,Data Type,Unique Values,Missing Values,Minimum,Maximum,Example Values
0,EmpNumber,str,1200,0,-,-,"[E1001000, E1001006, E1001007, E1001009, E1001..."
1,Age,int64,43,0,18,60,"[18, 19, 20, 21, 22, 23, 24, 25, 26, 27]"
2,Gender,str,2,0,-,-,"[Male, Female]"
3,EducationBackground,str,6,0,-,-,"[Marketing, Life Sciences, Human Resources, Me..."
4,MaritalStatus,str,3,0,-,-,"[Single, Married, Divorced]"
5,EmpDepartment,str,6,0,-,-,"[Sales, Human Resources, Development, Data Sci..."
6,EmpJobRole,str,19,0,-,-,"[Sales Executive, Manager, Developer, Sales Re..."
7,BusinessTravelFrequency,str,3,0,-,-,"[Travel_Rarely, Travel_Frequently, Non-Travel]"
8,DistanceFromHome,int64,29,0,1,29,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]"
9,EmpEducationLevel,int64,5,0,1,5,"[1, 2, 3, 4, 5]"
10,EmpEnvironmentSatisfaction,int64,4,0,1,4,"[1, 2, 3, 4]"
11,EmpHourlyRate,int64,71,0,30,100,"[30, 31, 32, 33, 34, 35, 36, 37, 38, 39]"
12,EmpJobInvolvement,int64,4,0,1,4,"[1, 2, 3, 4]"
13,EmpJobLevel,int64,5,0,1,5,"[1, 2, 3, 4, 5]"
14,EmpJobSatisfaction,int64,4,0,1,4,"[1, 2, 3, 4]"
15,NumCompaniesWorked,int64,10,0,0,9,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]"
16,OverTime,str,2,0,-,-,"[No, Yes]"
17,EmpLastSalaryHikePercent,int64,15,0,11,25,"[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]"
18,EmpRelationshipSatisfaction,int64,4,0,1,4,"[1, 2, 3, 4]"
19,TotalWorkExperienceInYears,int64,40,0,0,40,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]"
20,TrainingTimesLastYear,int64,7,0,0,6,"[0, 1, 2, 3, 4, 5, 6]"
21,EmpWorkLifeBalance,int64,4,0,1,4,"[1, 2, 3, 4]"
22,ExperienceYearsAtThisCompany,int64,37,0,0,40,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]"
23,ExperienceYearsInCurrentRole,int64,19,0,0,18,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]"
24,YearsSinceLastPromotion,int64,16,0,0,15,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]"
25,YearsWithCurrManager,int64,18,0,0,17,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]"
26,Attrition,str,2,0,-,-,"[No, Yes]"
27,PerformanceRating,int64,3,0,2,4,"[2, 3, 4]"

In [17]:
# Frequency distribution of categorical variables

for column in categorical_columns:
    print("=" * 70)
    print(f"{column}")
    print("=" * 70)
    print(df[column].value_counts())
    print()

======================================================================
EmpNumber
======================================================================
EmpNumber
E1001000    1
E1001006    1
E1001007    1
E1001009    1
E1001010    1
           ..
E100992     1
E100993     1
E100994     1
E100995     1
E100998     1
Name: count, Length: 1200, dtype: int64

======================================================================
Gender
======================================================================
Gender
Male      725
Female    475
Name: count, dtype: int64

======================================================================
EducationBackground
======================================================================
EducationBackground
Life Sciences       492
Medical             384
Marketing           137
Technical Degree    100
Other                66
Human Resources      21
Name: count, dtype: int64

======================================================================
MaritalStatus
======================================================================
MaritalStatus
Married     548
Single      384
Divorced    268
Name: count, dtype: int64

======================================================================
EmpDepartment
======================================================================
EmpDepartment
Sales                     373
Development               361
Research & Development    343
Human Resources            54
Finance                    49
Data Science               20
Name: count, dtype: int64

======================================================================
EmpJobRole
======================================================================
EmpJobRole
Sales Executive              270
Developer                    236
Manager R&D                   94
Research Scientist            77
Sales Representative          69
Laboratory Technician         64
Senior Developer              52
Manager                       51
Finance Manager               49
Human Resources               45
Technical Lead                38
Manufacturing Director        33
Healthcare Representative     33
Data Scientist                20
Research Director             19
Business Analyst              16
Senior Manager R&D            15
Delivery Manager              12
Technical Architect            7
Name: count, dtype: int64

======================================================================
BusinessTravelFrequency
======================================================================
BusinessTravelFrequency
Travel_Rarely        846
Travel_Frequently    222
Non-Travel           132
Name: count, dtype: int64

======================================================================
OverTime
======================================================================
OverTime
No     847
Yes    353
Name: count, dtype: int64

======================================================================
Attrition
======================================================================
Attrition
No     1022
Yes     178
Name: count, dtype: int64

In [18]:
# Detailed summary of numerical variables

numerical_summary = df[numerical_columns].describe().T

numerical_summary

,count,mean,std,min,25%,50%,75%,max
Age,1200.0,36.918333,9.087289,18.0,30.0,36.0,43.0,60.0
DistanceFromHome,1200.0,9.165833,8.176636,1.0,2.0,7.0,14.0,29.0
EmpEducationLevel,1200.0,2.892500,1.044120,1.0,2.0,3.0,4.0,5.0
EmpEnvironmentSatisfaction,1200.0,2.715833,1.090599,1.0,2.0,3.0,4.0,4.0
EmpHourlyRate,1200.0,65.981667,20.211302,30.0,48.0,66.0,83.0,100.0
EmpJobInvolvement,1200.0,2.731667,0.707164,1.0,2.0,3.0,3.0,4.0
EmpJobLevel,1200.0,2.067500,1.107836,1.0,1.0,2.0,3.0,5.0
EmpJobSatisfaction,1200.0,2.732500,1.100888,1.0,2.0,3.0,4.0,4.0
NumCompaniesWorked,1200.0,2.665000,2.469384,0.0,1.0,2.0,4.0,9.0
EmpLastSalaryHikePercent,1200.0,15.222500,3.625918,11.0,12.0,14.0,18.0,25.0
EmpRelationshipSatisfaction,1200.0,2.725000,1.075642,1.0,2.0,3.0,4.0,4.0
TotalWorkExperienceInYears,1200.0,11.330000,7.797228,0.0,6.0,10.0,15.0,40.0
TrainingTimesLastYear,1200.0,2.785833,1.263446,0.0,2.0,3.0,3.0,6.0
EmpWorkLifeBalance,1200.0,2.744167,0.699374,1.0,2.0,3.0,3.0,4.0
ExperienceYearsAtThisCompany,1200.0,7.077500,6.236899,0.0,3.0,5.0,10.0,40.0
ExperienceYearsInCurrentRole,1200.0,4.291667,3.613744,0.0,2.0,3.0,7.0,18.0
YearsSinceLastPromotion,1200.0,2.194167,3.221560,0.0,0.0,1.0,3.0,15.0
YearsWithCurrManager,1200.0,4.105000,3.541576,0.0,2.0,3.0,7.0,17.0
PerformanceRating,1200.0,2.948333,0.518866,2.0,3.0,3.0,3.0,4.0

In [19]:
# Inspect the Data Definitions sheet

data_definitions = pd.read_excel(
    file_path,
    sheet_name="Data Definitions"
)

print("Shape:", data_definitions.shape)

display(data_definitions)

Shape: (36, 2)

                    Unnamed: 0         Unnamed: 1
0                          NaN                NaN
1            EmpEducationLevel  1 'Below College'
2                          NaN        2 'College'
3                          NaN       3 'Bachelor'
4                          NaN         4 'Master'
5                          NaN         5 'Doctor'
6                          NaN                NaN
7   EmpEnvironmentSatisfaction            1 'Low'
8                          NaN         2 'Medium'
9                          NaN           3 'High'
10                         NaN      4 'Very High'
11                         NaN                NaN
12           EmpJobInvolvement            1 'Low'
13                         NaN         2 'Medium'
14                         NaN           3 'High'
15                         NaN      4 'Very High'
16                         NaN                NaN
17          EmpJobSatisfaction            1 'Low'
18                         NaN         2 'Medium'
19                         NaN           3 'High'
20                         NaN      4 'Very High'
21                         NaN                NaN
22           PerformanceRating            1 'Low'
23                         NaN           2 'Good'
24                         NaN      3 'Excellent'
25                         NaN    4 'Outstanding'
26                         NaN                NaN
27    RelationshipSatisfaction            1 'Low'
28                         NaN         2 'Medium'
29                         NaN           3 'High'
30                         NaN      4 'Very High'
31                         NaN                NaN
32          EmpWorkLifeBalance            1 'Bad'
33                         NaN           2 'Good'
34                         NaN         3 'Better'
35                         NaN           4 'Best'

### 1.9 Data Quality Assessment

After the initial data understanding, additional quality checks are performed to identify inconsistent categorical values and logically inconsistent employee experience records.

The checks are performed before feature engineering and modeling to ensure that the working dataset is suitable for further analysis.

In [20]:
# Check unique values of categorical variables
# to identify possible inconsistencies in category labels

categorical_columns = [
    "Gender",
    "EducationBackground",
    "MaritalStatus",
    "EmpDepartment",
    "EmpJobRole",
    "BusinessTravelFrequency",
    "OverTime",
    "Attrition"
]

for column in categorical_columns:
    print("=" * 70)
    print(column)
    print("=" * 70)
    print(df[column].value_counts(dropna=False))
    print()

======================================================================
Gender
======================================================================
Gender
Male      725
Female    475
Name: count, dtype: int64

======================================================================
EducationBackground
======================================================================
EducationBackground
Life Sciences       492
Medical             384
Marketing           137
Technical Degree    100
Other                66
Human Resources      21
Name: count, dtype: int64

======================================================================
MaritalStatus
======================================================================
MaritalStatus
Married     548
Single      384
Divorced    268
Name: count, dtype: int64

======================================================================
EmpDepartment
======================================================================
EmpDepartment
Sales                     373
Development               361
Research & Development    343
Human Resources            54
Finance                    49
Data Science               20
Name: count, dtype: int64

======================================================================
EmpJobRole
======================================================================
EmpJobRole
Sales Executive              270
Developer                    236
Manager R&D                   94
Research Scientist            77
Sales Representative          69
Laboratory Technician         64
Senior Developer              52
Manager                       51
Finance Manager               49
Human Resources               45
Technical Lead                38
Manufacturing Director        33
Healthcare Representative     33
Data Scientist                20
Research Director             19
Business Analyst              16
Senior Manager R&D            15
Delivery Manager              12
Technical Architect            7
Name: count, dtype: int64

======================================================================
BusinessTravelFrequency
======================================================================
BusinessTravelFrequency
Travel_Rarely        846
Travel_Frequently    222
Non-Travel           132
Name: count, dtype: int64

======================================================================
OverTime
======================================================================
OverTime
No     847
Yes    353
Name: count, dtype: int64

======================================================================
Attrition
======================================================================
Attrition
No     1022
Yes     178
Name: count, dtype: int64

### 1.10 Logical Consistency Checks

Logical consistency checks are performed on employee experience-related variables.

The purpose is to identify records where the relationship between different experience measures appears inconsistent, such as experience in the current role exceeding total experience at the company.

In [21]:
# Logical consistency checks for experience-related variables

check_current_role = (
    df["ExperienceYearsInCurrentRole"]
    > df["ExperienceYearsAtThisCompany"]
)

check_company_experience = (
    df["ExperienceYearsAtThisCompany"]
    > df["TotalWorkExperienceInYears"]
)

check_manager_experience = (
    df["YearsWithCurrManager"]
    > df["ExperienceYearsAtThisCompany"]
)

print(
    "Current role experience > company experience:",
    check_current_role.sum()
)

print(
    "Company experience > total work experience:",
    check_company_experience.sum()
)

print(
    "Manager experience > company experience:",
    check_manager_experience.sum()
)

Current role experience > company experience: 0
Company experience > total work experience: 0
Manager experience > company experience: 0

### 1.11 Target Variable Validation

The target variable is validated to ensure that all observed performance ratings correspond to the defined performance-rating categories provided in the project data definitions.

In [22]:
# Validate target values

expected_performance_ratings = [2, 3, 4]

invalid_target_records = df[
    ~df["PerformanceRating"].isin(expected_performance_ratings)
]

print(
    "Number of records with invalid PerformanceRating:",
    len(invalid_target_records)
)

print("\nObserved PerformanceRating values:")
print(sorted(df["PerformanceRating"].unique()))

Number of records with invalid PerformanceRating: 0

Observed PerformanceRating values:
[np.int64(2), np.int64(3), np.int64(4)]

### 1.12 Data Cleaning

Based on the data-quality checks performed above, the dataset does not contain missing values, duplicate records, invalid target values, or identified logical inconsistencies in the employee experience variables.

Therefore, no observations are removed at this stage.

A cleaned working copy is created to maintain a clear processing workflow while preserving the original raw dataset unchanged.

In [23]:
# Create a clean working copy
df_clean = df.copy()

print("Data cleaning completed.")
print(f"Rows    : {df_clean.shape[0]}")
print(f"Columns : {df_clean.shape[1]}")

print("\nMissing values:")
print(df_clean.isnull().sum().sum())

print("\nDuplicate rows:")
print(df_clean.duplicated().sum())

Data cleaning completed.
Rows    : 1200
Columns : 28

Missing values:
0

Duplicate rows:
0

### 1.13 Feature Classification

The variables are classified according to their role and measurement type before feature engineering.

The classification distinguishes:

- Target variable
- Identifier variable
- Ordinal variables, where the numerical levels represent an ordered scale
- Nominal categorical variables, where categories do not have a natural numerical order
- Numerical variables, representing measurable quantities or counts

This classification is used to determine the appropriate preprocessing approach during model development.

In [24]:
# Target variable
target_column = "PerformanceRating"

# Identifier variable
identifier_columns = [
    "EmpNumber"
]

# Ordinal variables
ordinal_columns = [
    "EmpEducationLevel",
    "EmpEnvironmentSatisfaction",
    "EmpJobInvolvement",
    "EmpJobSatisfaction",
    "EmpRelationshipSatisfaction",
    "EmpWorkLifeBalance"
]

# Nominal categorical variables
categorical_columns = [
    "Gender",
    "EducationBackground",
    "MaritalStatus",
    "EmpDepartment",
    "EmpJobRole",
    "BusinessTravelFrequency",
    "OverTime",
    "Attrition"
]

# Numerical variables
numerical_columns = [
    "Age",
    "DistanceFromHome",
    "EmpHourlyRate",
    "EmpJobLevel",
    "NumCompaniesWorked",
    "EmpLastSalaryHikePercent",
    "TotalWorkExperienceInYears",
    "TrainingTimesLastYear",
    "ExperienceYearsAtThisCompany",
    "ExperienceYearsInCurrentRole",
    "YearsSinceLastPromotion",
    "YearsWithCurrManager"
]

# Display classification
feature_classification = pd.DataFrame({
    "Feature_Type": (
        ["Target"] +
        ["Identifier"] * len(identifier_columns) +
        ["Ordinal"] * len(ordinal_columns) +
        ["Nominal Categorical"] * len(categorical_columns) +
        ["Numerical"] * len(numerical_columns)
    ),
    "Feature": (
        [target_column] +
        identifier_columns +
        ordinal_columns +
        categorical_columns +
        numerical_columns
    )
})

display(feature_classification)

print("Total classified columns:", len(feature_classification))
print("Original dataset columns :", len(df_clean.columns))

           Feature_Type                       Feature
0                Target             PerformanceRating
1            Identifier                     EmpNumber
2               Ordinal             EmpEducationLevel
3               Ordinal    EmpEnvironmentSatisfaction
4               Ordinal             EmpJobInvolvement
5               Ordinal            EmpJobSatisfaction
6               Ordinal   EmpRelationshipSatisfaction
7               Ordinal            EmpWorkLifeBalance
8   Nominal Categorical                        Gender
9   Nominal Categorical           EducationBackground
10  Nominal Categorical                 MaritalStatus
11  Nominal Categorical                 EmpDepartment
12  Nominal Categorical                    EmpJobRole
13  Nominal Categorical       BusinessTravelFrequency
14  Nominal Categorical                      OverTime
15  Nominal Categorical                     Attrition
16            Numerical                           Age
17            Numerical              DistanceFromHome
18            Numerical                 EmpHourlyRate
19            Numerical                   EmpJobLevel
20            Numerical            NumCompaniesWorked
21            Numerical      EmpLastSalaryHikePercent
22            Numerical    TotalWorkExperienceInYears
23            Numerical         TrainingTimesLastYear
24            Numerical  ExperienceYearsAtThisCompany
25            Numerical  ExperienceYearsInCurrentRole
26            Numerical       YearsSinceLastPromotion
27            Numerical          YearsWithCurrManager

Total classified columns: 28
Original dataset columns : 28

### 1.14 Feature Engineering and Transformation

Feature engineering and transformation decisions are based on the variable classification and the data definitions provided with the dataset.

The ordinal variables are retained in their existing ordered numerical representation because their levels have a meaningful order.

Nominal categorical variables are retained in categorical form at this stage. They will be encoded during model development using a preprocessing pipeline.

Numerical variables are retained in their original representation. Scaling will be applied within the model-specific preprocessing pipeline where required.

The employee identifier `EmpNumber` is excluded from the modeling features because it is an identifier rather than an employee characteristic.

The target variable `PerformanceRating` is kept separately from the predictor variables.

No artificial features are created at this stage because the available variables already represent employee characteristics, job-related factors, satisfaction measures, experience measures, and organizational attributes required for the analysis.

In [25]:
# Create the modeling feature set by excluding the identifier and target
X = df_clean.drop(
    columns=[target_column] + identifier_columns
)

y = df_clean[target_column].copy()

print("Predictor dataset shape:", X.shape)
print("Target shape           :", y.shape)

print("\nPredictor columns:")
print(X.columns.tolist())

print("\nTarget distribution:")
print(y.value_counts().sort_index())

Predictor dataset shape: (1200, 26)
Target shape           : (1200,)

Predictor columns:
['Age', 'Gender', 'EducationBackground', 'MaritalStatus', 'EmpDepartment', 'EmpJobRole', 'BusinessTravelFrequency', 'DistanceFromHome', 'EmpEducationLevel', 'EmpEnvironmentSatisfaction', 'EmpHourlyRate', 'EmpJobInvolvement', 'EmpJobLevel', 'EmpJobSatisfaction', 'NumCompaniesWorked', 'OverTime', 'EmpLastSalaryHikePercent', 'EmpRelationshipSatisfaction', 'TotalWorkExperienceInYears', 'TrainingTimesLastYear', 'EmpWorkLifeBalance', 'ExperienceYearsAtThisCompany', 'ExperienceYearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager', 'Attrition']

Target distribution:
PerformanceRating
2    194
3    874
4    132
Name: count, dtype: int64

### 1.15 Prepare Modeling Dataset

The final modeling dataset is prepared from the cleaned employee data.

The employee identifier is excluded because it does not represent a predictive employee characteristic. The target variable is kept separately from the predictor variables.

The processed dataset retains the original feature representations at this stage. Encoding of nominal categorical variables and scaling of numerical variables will be performed later within the model-training preprocessing pipelines.

The final dataset is validated before being saved to the processed-data directory.

In [26]:
# Create the final modeling dataset
modeling_data = X.copy()

# Add the target variable
modeling_data[target_column] = y

print("Final modeling dataset shape:", modeling_data.shape)

print("\nMissing values:")
print(modeling_data.isnull().sum().sum())

print("\nDuplicate rows:")
print(modeling_data.duplicated().sum())

print("\nTarget distribution:")
print(modeling_data[target_column].value_counts().sort_index())

print("\nData types:")
display(modeling_data.dtypes.to_frame(name="Data Type"))

Final modeling dataset shape: (1200, 27)

Missing values:
0

Duplicate rows:
0

Target distribution:
PerformanceRating
2    194
3    874
4    132
Name: count, dtype: int64

Data types:

                             Data Type
Age                              int64
Gender                             str
EducationBackground                str
MaritalStatus                      str
EmpDepartment                      str
EmpJobRole                         str
BusinessTravelFrequency            str
DistanceFromHome                 int64
EmpEducationLevel                int64
EmpEnvironmentSatisfaction       int64
EmpHourlyRate                    int64
EmpJobInvolvement                int64
EmpJobLevel                      int64
EmpJobSatisfaction               int64
NumCompaniesWorked               int64
OverTime                           str
EmpLastSalaryHikePercent         int64
EmpRelationshipSatisfaction      int64
TotalWorkExperienceInYears       int64
TrainingTimesLastYear            int64
EmpWorkLifeBalance               int64
ExperienceYearsAtThisCompany     int64
ExperienceYearsInCurrentRole     int64
YearsSinceLastPromotion          int64
YearsWithCurrManager             int64
Attrition                          str
PerformanceRating                int64

### 1.16 Save Processed Dataset

The validated modeling dataset is saved in the processed-data directory.

The raw dataset remains unchanged in the raw-data directory. The processed dataset serves as the canonical input for exploratory analysis and model development.

In [27]:
import os

# Path for the processed dataset
processed_path = "../../data/processed/employee_performance_processed.csv"

# Create the processed directory if it does not already exist
os.makedirs(os.path.dirname(processed_path), exist_ok=True)

# Save the processed dataset
modeling_data.to_csv(
    processed_path,
    index=False
)

print("Processed dataset saved successfully.")
print("Path:", processed_path)
print("Shape:", modeling_data.shape)

Processed dataset saved successfully.
Path: ../../data/processed/employee_performance_processed.csv
Shape: (1200, 27)

In [28]:
# Verify the saved file
processed_check = pd.read_csv(processed_path)

print("Processed file loaded successfully.")
print("Shape:", processed_check.shape)

print("\nColumns:")
print(processed_check.columns.tolist())

Processed file loaded successfully.
Shape: (1200, 27)

Columns:
['Age', 'Gender', 'EducationBackground', 'MaritalStatus', 'EmpDepartment', 'EmpJobRole', 'BusinessTravelFrequency', 'DistanceFromHome', 'EmpEducationLevel', 'EmpEnvironmentSatisfaction', 'EmpHourlyRate', 'EmpJobInvolvement', 'EmpJobLevel', 'EmpJobSatisfaction', 'NumCompaniesWorked', 'OverTime', 'EmpLastSalaryHikePercent', 'EmpRelationshipSatisfaction', 'TotalWorkExperienceInYears', 'TrainingTimesLastYear', 'EmpWorkLifeBalance', 'ExperienceYearsAtThisCompany', 'ExperienceYearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager', 'Attrition', 'PerformanceRating']